'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
	''' </summary>
	' Этот класс создан автоматически классом StronglyTypedResourceBuilder
	' с помощью такого средства, как ResGen или Visual Studio.
	' Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
	' с параметром /str или перестройте свой проект VS.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Перезаписывает свойство CurrentUICulture текущего потока для всех
		'''   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property add_derived_table() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("add_derived_table", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property add_union_subquery() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("add_union_subquery", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_cascade() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_cascade", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_side_tree() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_side_tree", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_tile_horizontal() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_tile_horizontal", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property application_tile_vertical() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_tile_vertical", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property arrow_left() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("arrow_left", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property arrow_right() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("arrow_right", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property bricks() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("bricks", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property bullet_green() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("bullet_green", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property cancel() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("cancel", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property chart_organisation() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("chart_organisation", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property cog() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("cog", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property connect() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("connect", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property copy_union_subquery() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("copy_union_subquery", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property cut() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("cut", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property database() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("database", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property database_edit() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("database_edit", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property database_go() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("database_go", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property database_save() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("database_save", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property database_table() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("database_table", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property disconnect() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("disconnect", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property disk() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("disk", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property drive_disk() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("drive_disk", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property folder() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property folder_bullet_green() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("folder_bullet_green", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property folder_page() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("folder_page", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property folder_table() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("folder_table", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property help() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property info() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property new_object() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("new_object", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property page_copy() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("page_copy", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property page_paste() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("page_paste", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property page_white() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("page_white", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property query_properties() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("query_properties", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Bitmap.
		''' </summary>
		Friend ReadOnly Property run() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("run", resourceCulture)
				Return (CType(obj, Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property table() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("table", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property table_gear() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("table_gear", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property table_lightning() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("table_lightning", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property table_multiple() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("table_multiple", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property

		''' <summary>
		'''   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
		''' </summary>
		Friend ReadOnly Property table_sort() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("table_sort", resourceCulture)
				Return (CType(obj, Icon))
			End Get
		End Property
	End Module
End Namespace
