'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программным средством.
'     Версия среды выполнения: 4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
'     код создан повторно.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace Properties


	''' <summary>
	'''   Класс ресурсов со строгим типом для поиска локализованных строк и пр.
	''' </summary>
	' Этот класс был автоматически создан при помощи StronglyTypedResourceBuilder
	' класс с помощью таких средств, как ResGen или Visual Studio.
	' Для добавления или удаления члена измените файл .ResX, а затем перезапустите ResGen
	' с параметром /str или заново постройте свой VS-проект.
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")> _
	<System.Diagnostics.DebuggerNonUserCodeAttribute> _
	<System.Runtime.CompilerServices.CompilerGeneratedAttribute> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Возврат кэшированного экземпляра ResourceManager, используемого этим классом.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If (resourceMan Is Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("QueryTransformerCoreDemo.Properties.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Переопределяет свойство CurrentUICulture текущего потока для всех
		'''   подстановки ресурсов с помощью этого класса ресурсов со строгим типом.
		''' </summary>
		<System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set
				resourceCulture = value
			End Set
		End Property
	End Class
End Namespace
